### ISSUE TITLE
NumbaWarning:  Compilation is falling back to object mode WITH looplifting enabled

### ISSUE THREAD

**Issue by talhaanwarch** [mne-tools/mne-features#53] opened 2019-07-18 15:25 UTC
Greetings. I am working on kaggle kernals and every thing is working well. I created a new kernal and donwload the jupyter notebook file from previous kernal and uploaded to new kernal. 
I do 
!pip install git+https://github.com/mne-tools/mne-features.git#egg=mne_features
when i do 
from mne_features.feature_extraction import FeatureExtractor

i got the following error

/opt/conda/lib/python3.6/site-packages/mne_features/univariate.py:856: NumbaWarning: 
Compilation is falling back to object mode WITH looplifting enabled because Function "_higuchi_fd" failed type inference due to: Invalid use of Function(<built-in function empty>) with argument(s) of type(s): (tuple(OptionalType(int64) i.e. the type 'int64 or None' x 1))
 * parameterized
In definition 0:
    All templates rejected with literals.
In definition 1:
    All templates rejected without literals.
This error is usually caused by passing an argument of a type that is unsupported by the named function.
[1] During: resolving callee type: Function(<built-in function empty>)
[2] During: typing of call at /opt/conda/lib/python3.6/site-packages/mne_features/univariate.py (874)

File "../../opt/conda/lib/python3.6/site-packages/mne_features/univariate.py", line 874:
def _higuchi_fd(data, kmax):
    <source elided>
    for s in range(n_channels):
        lk = np.empty((kmax,))
        ^

  @nb.jit([nb.float64[:](nb.float64[:, :], nb.optional(nb.int64)),
/opt/conda/lib/python3.6/site-packages/mne_features/univariate.py:856: NumbaWarning: 
Compilation is falling back to object mode WITHOUT looplifting enabled because Function "_higuchi_fd" failed type inference due to: cannot determine Numba type of <class 'numba.dispatcher.LiftedLoop'>

File "../../opt/conda/lib/python3.6/site-packages/mne_features/univariate.py", line 873:
def _higuchi_fd(data, kmax):
    <source elided>
    higuchi = np.empty((n_channels,), dtype=data.dtype)
    for s in range(n_channels):
    ^

  @nb.jit([nb.float64[:](nb.float64[:, :], nb.optional(nb.int64)),
/opt/conda/lib/python3.6/site-packages/numba/compiler.py:725: NumbaWarning: Function "_higuchi_fd" was compiled in object mode without forceobj=True, but has lifted loops.

File "../../opt/conda/lib/python3.6/site-packages/mne_features/univariate.py", line 858:
         nb.float32[:](nb.float32[:, :], nb.optional(nb.int32))])
def _higuchi_fd(data, kmax):
^

  self.func_ir.loc))
/opt/conda/lib/python3.6/site-packages/numba/compiler.py:734: NumbaDeprecationWarning: 
Fall-back from the nopython compilation path to the object mode compilation path has been detected, this is deprecated behaviour.

For more information visit http://numba.pydata.org/numba-doc/latest/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit

File "../../opt/conda/lib/python3.6/site-packages/mne_features/univariate.py", line 858:
         nb.float32[:](nb.float32[:, :], nb.optional(nb.int32))])
def _higuchi_fd(data, kmax):
^

  warnings.warn(errors.NumbaDeprecationWarning(msg, self.func_ir.loc))
/opt/conda/lib/python3.6/site-packages/mne_features/univariate.py:856: NumbaWarning: 
Compilation is falling back to object mode WITH looplifting enabled because Function "_higuchi_fd" failed type inference due to: Invalid use of Function(<built-in function empty>) with argument(s) of type(s): (tuple(OptionalType(int32) i.e. the type 'int32 or None' x 1))
 * parameterized
In definition 0:
    All templates rejected with literals.
In definition 1:
    All templates rejected without literals.
This error is usually caused by passing an argument of a type that is unsupported by the named function.
[1] During: resolving callee type: Function(<built-in function empty>)
[2] During: typing of call at /opt/conda/lib/python3.6/site-packages/mne_features/univariate.py (874)

File "../../opt/conda/lib/python3.6/site-packages/mne_features/univariate.py", line 874:
def _higuchi_fd(data, kmax):
    <source elided>
    for s in range(n_channels):
        lk = np.empty((kmax,))
        ^

  @nb.jit([nb.float64[:](nb.float64[:, :], nb.optional(nb.int64)),
/opt/conda/lib/python3.6/site-packages/mne_features/univariate.py:856: NumbaWarning: 
Compilation is falling back to object mode WITHOUT looplifting enabled because Function "_higuchi_fd" failed type inference due to: cannot determine Numba type of <class 'numba.dispatcher.LiftedLoop'>

File "../../opt/conda/lib/python3.6/site-packages/mne_features/univariate.py", line 873:
def _higuchi_fd(data, kmax):
    <source elided>
    higuchi = np.empty((n_channels,), dtype=data.dtype)
    for s in range(n_channels):
    ^

  @nb.jit([nb.float64[:](nb.float64[:, :], nb.optional(nb.int64)),
/opt/conda/lib/python3.6/site-packages/numba/compiler.py:725: NumbaWarning: Function "_higuchi_fd" was compiled in object mode without forceobj=True, but has lifted loops.

File "../../opt/conda/lib/python3.6/site-packages/mne_features/univariate.py", line 858:
         nb.float32[:](nb.float32[:, :], nb.optional(nb.int32))])
def _higuchi_fd(data, kmax):
^

  self.func_ir.loc))
/opt/conda/lib/python3.6/site-packages/numba/compiler.py:734: NumbaDeprecationWarning: 
Fall-back from the nopython compilation path to the object mode compilation path has been detected, this is deprecated behaviour.

For more information visit http://numba.pydata.org/numba-doc/latest/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit

File "../../opt/conda/lib/python3.6/site-packages/mne_features/univariate.py", line 858:
         nb.float32[:](nb.float32[:, :], nb.optional(nb.int32))])
def _higuchi_fd(data, kmax):
^

  warnings.warn(errors.NumbaDeprecationWarning(msg, self.func_ir.loc))

**Comment by jbschiratti** [comment] 2019-07-18 15:45
Thank you @talhaanwarch for opening this issue.
This looks more like a warning than an error. Does this break you code?
I am using `numba==0.43.1` and was not able to reproduce this. Which version of numba are you using?

**Comment by talhaanwarch** [comment] 2019-07-18 15:58
In Previous kaggle kernal (created a week ago) , numba version is` 0.38.0` But in new kaggle kernal created today , numba version is `0.44.1` and its causing the above error. i will check whether it work on small data or give an error. Actually my pipe line take hours to complete. I will update you tomorrow about this

**Comment by jbschiratti** [comment] 2019-07-19 07:29
The warning you got is most certainly due to Numba failing to compile the `_higuchi_fd` function in Nopython mode. In this case, the compiler falls back to "object mode" (which provides no significant speed-up as compared to plain Python code).

The first issue with `_higuchi_fd` is that the (list of) signatures given to the Numba JIT decorator is incorrect. It currently is:

    [nb.float64[:](nb.float64[:, :], nb.optional(nb.int64)), nb.float32[:](nb.float32[:, :], nb.optional(nb.int32))]

but the `kmax` parameter is not optional and therefore, 

    [nb.float64[:](nb.float64[:, :], nb.int64), nb.float32[:](nb.float32[:, :], nb.int32)]

may be more correct.

Still, this does not fix the problem. Indeed,

```
import warnings

import numba as nb
import numpy as np
from math import floor, log


@nb.jit([nb.float64(nb.float64[:], nb.float64[:]),
         nb.float32(nb.float32[:], nb.float32[:])], nopython=True)
def _slope_lstsq(x, y):
    """Slope of a 1D least-squares regression.

    Utility function which returns the slope of the linear regression
    between x and y.

    Parameters
    ----------
    x : ndarray, shape (n_times,)

    y : ndarray, shape (n_times,)

    Returns
    -------
    float
    """
    n_times = x.shape[0]
    sx2 = 0
    sx = 0
    sy = 0
    sxy = 0
    for j in range(n_times):
        sx2 += x[j] ** 2
        sx += x[j]
        sxy += x[j] * y[j]
        sy += y[j]
    den = n_times * sx2 - (sx ** 2)
    num = n_times * sxy - sx * sy
    return num / den


with warnings.catch_warnings():

    warnings.simplefilter('always')

    @nb.jit([nb.float64[:](nb.float64[:, :], nb.int64),
             nb.float32[:](nb.float32[:, :], nb.int32)])
    def _higuchi_fd(data, kmax):
        """Utility function for :func:`compute_higuchi_fd`.

        Parameters
        ----------
        data : ndarray, shape (n_channels, n_times)

        kmax : int

        Returns
        -------
        output : ndarray, shape (n_channels,)
        """
        n_channels, n_times = data.shape
        higuchi = np.empty((n_channels,), dtype=data.dtype)
        for s in range(n_channels):
            lk = np.empty((kmax,))
            x_reg = np.empty((kmax,))
            y_reg = np.empty((kmax,))
            for k in range(1, kmax + 1):
                lm = np.empty((k,))
                for m in range(k):
                    ll = 0
                    n_max = floor((n_times - m - 1) / k)
                    n_max = int(n_max)
                    for j in range(1, n_max):
                        ll += abs(data[s, m + j * k] - data[s, m + (j - 1) * k])
                    ll /= k
                    ll *= (n_times - 1) / (k * n_max)
                    lm[m] = ll
                # Mean of lm
                m_lm = 0
                for m in range(k):
                    m_lm += lm[m]
                m_lm /= k
                lk[k - 1] = m_lm
                x_reg[k - 1] = log(1. / k)
                y_reg[k - 1] = log(m_lm)
            higuchi[s] = 1.
        return higuchi
```
raises the same `NumbaWarning` as the one you reported. The real issue is with the `kmax` parameter whose type is incorrect: Numba expects `int64` and sees `int32`. This issue is fixed by adding `kmax = np.int64(kmax)` just above `lk = np.empty((kmax,))`.

I'll make a PR to fix this.

**Comment by jbschiratti** [comment] 2019-07-19 08:29
@agramfort As it is now, we do not have a way of knowing if Numba compiled the functions correctly.
What about adding a test for that in `test_univariate.py`? I was thinking about something like:

```
def test_numba_compile():

    _jitted_funcs = [_accumulate_max, _accumulate_min, _accumulate_std,
                     _hurst_exp_compute_rs, _tk_energy, _higuchi_fd]
    with warnings.catch_warnings():

        warnings.simplefilter('error')
        for func in _jitted_funcs:
            func.recompile()
```
Still, the test is not specific. It will fail if the compilation with Numba raises a warning.

**Comment by agramfort** [comment] 2019-07-19 09:25
what do you mean "compiled correctly"?

>

**Comment by jbschiratti** [comment] 2019-07-19 09:27
Ideally, not in object mode (as there is no improvement as compared to Python code) and without raising any `NumbaWarning`.

**Comment by agramfort** [comment] 2019-07-19 09:33
you want to make sure it compiles with nopython? @njit is not enough?

**Comment by jbschiratti** [comment] 2019-07-19 09:39
Yes you're right! `@nb.njit` (or `@nb.jit(nopython=True)`) is enough. No test needed, I think.

**Comment by agramfort** [comment] 2019-07-19 10:06
ok great. Iet's do this then

**Closed** 2019-07-19 14:43 UTC
